### ISSUE TITLE
Needs an appropriate license

### ISSUE THREAD

**Issue by jaysonvirissimo** [jameslawler/awesome-learn-portuguese#2]
It's typical for awesome lists to use the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license.

**Comment by jameslawler** [comment]
Thanks for that. I checked the official guide for awesome lists and you are right. I have updated it on the master branch. By the way, I saw your email, and I am happy to receive contributions. I will try to keep adding to it more frequently as I find new material.
